name: "✨ Luminaire Protocol"
run-name: "${{ inputs.kernel_version }} | ${{ inputs.build_system }} (${{ inputs.warming_mode == 'true' && 'Warming' || 'Build' }})"
on:
  workflow_dispatch:
    inputs:
      build_system:
        description: "Build System"
        type: choice
        default: "Kleaf - AOSP"
        options:
          - "Kleaf - AOSP"
          - "Make - Cirrus"
          - "Make - Neutron"
          - "Make - WeebX"
          - "Make - Zyc"
      kernel_version:
        description: "Kernel Version"
        type: choice
        default: "6.1"
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
          - "6.12"
      vanilla:
        description: "VANILLA"
        type: boolean
        default: true
      resukisu:
        description: "ReSukiSU"
        type: boolean
        default: false
      sukisu:
        description: "SukiSU-Ultra"
        type: boolean
        default: false
      susfs:
        description: "SuSFS"
        type: choice
        default: "enable"
        options:
          - "enable"
          - "disable"
      mountless_engine:
        description: "Mountless Engine"
        type: choice
        default: "none"
        options:
          - "none"
          - "nomount"
          - "zeromount"
      bbg:
        description: "BBG (Baseband Guard)"
        type: boolean
        default: true
      rekernel:
        description: "Re:Kernel (Binder/Signal Netlink)"
        type: boolean
        default: false
      droidspaces:
        description: "Droidspaces"
        type: boolean
        default: false
      update_arsenal:
        description: "Update Arsenal"
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
      enable_lto:
        description: "⚠️ LTO"
        type: choice
        default: "NONE"
        options:
          - "NONE"
          - "THIN"
          - "FULL"
      warming_mode:
        description: "Warming Mode (skip release)"
        type: choice
        default: "false"
        options:
          - "false"
          - "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Luminaire:
    uses: ./.github/workflows/_kernel-build.yml
    with:
      build_system:    ${{ inputs.build_system }}
      vanilla:         ${{ inputs.vanilla }}
      resukisu:        ${{ inputs.resukisu }}
      sukisu:          ${{ inputs.sukisu }}
      susfs:           ${{ inputs.susfs == 'enable' }}
      kernel_version:  ${{ inputs.kernel_version }}
      update_arsenal:  ${{ inputs.update_arsenal }}
      enable_lto:      ${{ inputs.enable_lto }}
      warming_mode:    ${{ inputs.warming_mode }}
      addons:          "${{ inputs.bbg && 'bbg' || '' }}${{ inputs.rekernel && ',rekernel' || '' }}${{ inputs.droidspaces && ',droidspaces' || '' }}${{ inputs.mountless_engine != 'none' && format(',{0}', inputs.mountless_engine) || '' }}"
    secrets:
      PERSONAL_TOKEN:              ${{ secrets.PERSONAL_TOKEN }}
      TELEGRAM_BOT_TOKEN:          ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:            ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_THREAD_ID_ARTIFACT: ${{ secrets.TELEGRAM_THREAD_ID_ARTIFACT }}
      TELEGRAM_THREAD_ID_LOG:      ${{ secrets.TELEGRAM_THREAD_ID_LOG }}
