name: "✨ Luminaire Protocol"
run-name: "✨ ${{ inputs.kernel_version }} | ${{ inputs.build_system }}"

on:
  workflow_dispatch:
    inputs:
      build_system:
        description: "Build System"
        type: choice
        default: "MAKE"
        options:
          - "MAKE"
          - "KLEAF"
      kernel_version:
        description: "Kernel Version"
        type: choice
        default: "6.1"
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
          - "6.12"
      vanilla:
        description: "VANILLA"
        type: boolean
        default: true
      update_arsenal:
        description: "Update Arsenal"
        type: choice
        default: "no"
        options:
          - "yes"
          - "no"
      enable_lto:
        description: "⚠️ LTO"
        type: choice
        default: "NONE"
        options:
          - "NONE"
          - "THIN"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # ======================================================
  # 🧮 PREPARE MATRIX
  # ======================================================
  prepare-matrix:
    name: "Prepare Matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}

    steps:
      - name: "🧮 Build Variant Matrix"
        id: set
        run: |
          variants=()
          ${{ inputs.vanilla }} && variants+=("VANILLA")

          if [ ${#variants[@]} -eq 0 ]; then
            echo "No variants selected!"
            exit 1
          fi

          echo "matrix=$(jq -cn '$ARGS.positional' --args "${variants[@]}")" >> $GITHUB_OUTPUT

  # ======================================================
  # 🏗️ BUILD
  # ======================================================
  build:
    name: "Luminaire"
    needs: prepare-matrix
    strategy:
      matrix:
        variant: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/_kernel-build.yml
    with:
      build_system:   ${{ inputs.build_system }}
      variant:        ${{ matrix.variant }}
      kernel_version: ${{ inputs.kernel_version }}
      update_arsenal: ${{ inputs.update_arsenal }}
      enable_lto:     ${{ inputs.enable_lto }}
    secrets:
      PERSONAL_TOKEN:              ${{ secrets.PERSONAL_TOKEN }}
      TELEGRAM_BOT_TOKEN:          ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:            ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_THREAD_ID_ARTIFACT: ${{ secrets.TELEGRAM_THREAD_ID_ARTIFACT }}
      TELEGRAM_THREAD_ID_LOG:      ${{ secrets.TELEGRAM_THREAD_ID_LOG }}
